### PR TITLE
competing attempt to bump mathlib and update blueprint

### PR DESCRIPTION
**Pull request by emilyriehl**
@gio256 we were working in parallel. Help me figure out which to merge?

### CODE REVIEW

**Comment by emilyriehl** [comment]
Note the blueprint is actually broken: this version can't find `Nerve.quasicategory` in mathlib.

**Comment by gio256** [comment]
@emilyriehl apologies for the lack of coordination. I would say just merge this one, as it does all the work I have yet to do (updating the blueprint and moving `ForMathlib/AlgebraicTopology/SimplicialSet/Quasicategory.lean`)

**Comment by emilyriehl** [comment]
@pitmonticone sorry to bug you again. I'm having another issue with a mathlib declaration that the blueprint is having trouble finding. This is from a relatively new PR by @gio256.

**Comment by pitmonticone** [comment]
@emilyriehl fixed

**Pull request merged**
